name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up SSL certificates
        run: |
          mkdir -p $HOME/ssl
          echo "${{ secrets.SSL_PRIVATE_KEY }}" > $HOME/ssl/privkey.pem
          echo "${{ secrets.SSL_CERT_CHAIN }}" > $HOME/ssl/fullchain.pem

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: absendo/docker-image:latest

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull absendo/docker-image:latest
            docker stop absendo-docker || true
            docker rm absendo-docker || true
            docker exec absendo-docker mkdir -p /etc/ssl/
            docker exec echo "meep" > /etc/ssl/meep.txt
            docker exec echo "meep" > /etc/meep.txt
            docker cp $HOME/ssl/privkey.pem absendo-docker:/etc/ssl/privkey.pem
            docker cp $HOME/ssl/fullchain.pem absendo-docker:/etc/ssl/fullchain.pem
            docker run -d --restart always --name absendo-docker -p 3001:3001 \
              -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
              -e SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} \
              absendo/docker-image:latest
